---
title: "SSRS_motus_data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## MotusRBook

Based on examples in **Motus R Book**
by Tara L. Crewe, Zoe Crysler, and Philip Taylor
https://beta.motus.org/MotusRBook/


```{r setup}
library(motus)
library(lubridate)
library(dplyr)
Sys.setenv(TZ = "UTC")

# Kern River Valley Tri-colored Blackbird Study
proj.num = 247 

# rth, lc4, canebrake
df.serno = c("CTT-957865AC5BF7", "CTT-C0612F7F986B", "CTT-27532C924059")

# California-Shorebird Migration and Drought Study
proj.num = 458 

# Pixley NWR, Colusa NWR, Staten Island, Bird Haven, Montna Farms
df.serno = c("CTT-140682CCEB52", "CTT-9697596E76D6", "CTT-BF45E4FCD972",
             "CTT-F51A7C862D57", "CTT-2CFE3C766E92")


# Project
## First time
proj.sql.motus <- tagme(projRecv = proj.num, new = TRUE, update = TRUE)

# Receivers


motusLogout()
```

## Update files

You can update individual sql files or all at once.

```{r update}
# Project
## Update
proj.sql.motus <- tagme(projRecv = proj.num, new = FALSE, update = TRUE)

# Kern River Valley Tri-colored Blackbird Study
rec.names = paste0(c("rth", "lc4", "canebrake"), ".sql.motus")

# California-Shorebird Migration and Drought Study
rec.names = paste0(c("pixley", "colusa", "staten", "birdhaven", "montna"), ".sql.motus")

# Individually
rec.names[1] <- tagme(projRecv = df.serno[1], new = TRUE, update = TRUE)
rec.names[2] <- tagme(projRecv = df.serno[2], new = TRUE, update = TRUE)
rec.names[3] <- tagme(projRecv = df.serno[3], new = TRUE, update = TRUE)
rec.names[4] <- tagme(projRecv = df.serno[4], new = TRUE, update = TRUE)
rec.names[5] <- tagme(projRecv = df.serno[5], new = TRUE, update = TRUE)

# All at once with variable assignment so it is comparable to the individual way
for (k in 1:length(df.serno)) {
  assign(rec.names[k], tagme(df.serno[k], update = TRUE))
}

# All at once without varialbe assignment
# for (k in 1:length(df.serno)) {
#   tagme(df.serno[k], update = TRUE)
# }

# All at once for all of your projects
### Beware this till take a really long tims
# tagme()

# This will get data on all projects and receiver deployments
## Access this in recDeps table in proj.sql.motus
metadata(proj.sql.motus)

motusLogout()
```

## Accessing tables

Once you have the .motus files downloaded and updated, you can look at them 
using a database viewer like dBeaver by connecting an sQLite connection to the 
location on disk.

```{r data}
library(DBI)
library(RSQLite)

file.name <- dbConnect(SQLite(), getwd())
dbListTables(file.name)
dbListFields(file.name, "species")
tbl.alltags <- tbl(sql.motus, "alltags") # virtual table
# Filter the data
tbl.TRBL <- tbl(sql.motus, "alltags") %>%
  filter(speciesEN == "Tri-colored Blackbird") %>%
  collect()

# Get the daily median location of GPS points for these data
TRBL.GPS <- getGPS(src = sql.motus, data = tbl.TRBL)

# Get flat table
df.alltags <- tbl.alltags %>% 
  collect() %>% 
  as.data.frame()
```

